# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end
# App Server 1
  config.vm.define "app1" do |app|
    app.vm.hostname = "ocr-app1.test"
    app.vm.network :private_network, ip:"192.168.60.4"
  end
# App Server 1
  config.vm.define "app2" do |app|
    app.vm.hostname = "ocr-app2.test"
    app.vm.network :private_network, ip:"192.168.60.5"
  end
# App Server 2
  config.vm.define "db" do |db|
    db.vm.hostname = "ocr-db.test"
    db.vm.network :private_network, ip:"192.168.60.6"
 end
end
