# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/ubuntu1604"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end
# App Server 1
  config.vm.define "solr1" do |solr|
    solr.vm.hostname = "ocr-solr1.test"
    solr.vm.network :private_network, ip:"192.168.60.20"
  end
end
