# -*- mode: ruby -*-                                                             
# vi: set ft=ruby :                                                              
                                                                                 
Vagrant.configure("2") do |config|

# App Server 1
  config.vm.define "app1" do |centos|
    centos.vm.box= "geerlingguy/centos7"
    centos.vm.hostname = "ocr-app1.test"
    centos.vm.network :private_network, ip:"192.168.60.70"
    centos.ssh.insert_key = false
    centos.vm.synced_folder ".", "/vagrant", disabled: true
    centos.vm.provider :virtualbox do |v|
      v.memory = 256
      v.linked_clone = true
    end
  end

# App Server 2
  config.vm.define "app2" do |ubuntu|
    ubuntu.vm.box = "geerlingguy/ubuntu1604"
    ubuntu.vm.hostname = "ocr-app2.test"
    ubuntu.vm.network :private_network, ip:"192.168.60.80"
    ubuntu.ssh.insert_key = false
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntu.vm.provider :virtualbox do |v|
      v.memory = 256
      v.linked_clone = true
    end
  end
end
